### ISSUE TITLE
 construct the mechanical tangent

### ISSUE THREAD

**Issue by saturn00000** [HenannResearchGroup/ElastomericFoam#1]
I would kindly ask, do we need to add few lines for  the mechanical tangent as follows (based on the spatial tangent, (**B.3**), page 23, https://doi.org/10.1016/j.jmps.2019.103701):
```
      do i=1,3
         do j=1,3
            do k=1,3
               do l=1,3
                  Ctang(i,j,k,l) = Ctang(i,j,k,l)
     +                - T_tau(i,l)*Iden(j,k)
               enddo
            enddo
         enddo
      enddo
```

Ref: https://doi.org/10.1016/j.jmps.2019.103701

https://github.com/HenannResearchGroup/NonlocalGranularRheology/blob/a55c0826da5609f626c6efe6f535978dbf649568/uel_granular_nonlocal_2D.for

**Comment by HenannResearchGroup** [comment]
Thanks for the question! The spatial tangents appearing in the loss of ellipticity analysis in Appendix B of the paper are slightly different from the Jacobian requested by the Abaqus UMAT subroutine, which is defined in terms of increments of the Kirchhoff stress. But both are similar and only differ by the terms you've highlighted above.

**Comment by saturn00000** [comment]
> Thanks for the question! The spatial tangents appearing in the loss of ellipticity analysis in Appendix B of the paper are slightly different from the Jacobian requested by the Abaqus UMAT subroutine, which is defined in terms of increments of the Kirchhoff stress. But both are similar and only differ by the terms you've highlighted above.

Thanks for your reply! I would kindly ask, what is **the exact Jacobian formulation for this UMAT**?

**Comment by HenannResearchGroup** [comment]
See attached file. [UMAT_Jacobian.pdf](https://github.com/HenannResearchGroup/ElastomericFoam/files/9275718/UMAT_Jacobian.pdf)

**Comment by saturn00000** [comment]
> See attached file. [UMAT_Jacobian.pdf](https://github.com/HenannResearchGroup/ElastomericFoam/files/9275718/UMAT_Jacobian.pdf)

**Great! Dear @ HenannResearchGroup,  Thanks a lot for your support!**

Kind regards!
